version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: antiai-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: antiai
      POSTGRES_PASSWORD: "311990"
      POSTGRES_DB: antiai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U antiai" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: antiai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
