import { test, expect } from '@playwright/test';
import * as path from 'path';

test.describe('Provenance Hunt Quest (e2e)', () => {
  // Use a predictable test image
  const fixturePath = path.resolve(__dirname, 'fixture.png');

  test('completes the full file drop to claim submission flow', async ({ page }) => {
    // Navigate to the drop zone
    await page.goto('/v');

    // Mock the backend API responses since the backend doesn't run during this UI E2E test
    await page.route('**/v1/subjects/*', route => {
      // Don't intercept the phash and resolve POST endpoints with this GET wildcard
      if (route.request().method() !== 'GET') return route.fallback();
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ hash: 'dummy-hash', mediaType: 'IMAGE', status: 'PENDING' })
      });
    });

    await page.route('**/v1/subjects/phash', route => route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ perceptualHash: '0000000000000000' })
    }));

    await page.route('**/v1/subjects/resolve', route => route.fulfill({
      status: 201,
      contentType: 'application/json',
      body: JSON.stringify({ hash: 'mock-hash-123' })
    }));

    await page.route('**/v1/subjects/*/attestations', route => route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ items: [] })
    }));

    await page.route('**/v1/identities/challenge', route => route.fulfill({
      status: 201,
      contentType: 'application/json',
      body: JSON.stringify({ nonce: 'mock-nonce-12345' })
    }));

    await page.route('**/v1/identities/register', route => route.fulfill({
      status: 201,
      contentType: 'application/json',
      body: JSON.stringify({ keyId: 'mock-key-id-123' })
    }));

    await page.route('**/v1/attestations', route => route.fulfill({
      status: 201,
      contentType: 'application/json',
      body: JSON.stringify({ success: true })
    }));

    const resolvePromise = page.waitForResponse((res) => res.url().includes('/v1/subjects/resolve') && res.status() === 201);

    // 1. Upload File
    await page.locator('input[type="file"]').setInputFiles(fixturePath);

    // Wait for the resolve step to finish and redirect
    const resolveRes = await resolvePromise;
    expect(resolveRes.ok()).toBeTruthy();

    const resolveData = await resolveRes.json();
    expect(resolveData.hash).toBeDefined();

    // The page should redirect to /v/[hash]
    await page.waitForURL(`**/v/*`);

    // 2. Submit Claim
    // Wait for the minimal host page to load and display the summary
    await expect(page.locator('text=Subject Details')).toBeVisible();

    // Fill in the form
    await page.fill('textarea[placeholder="e.g. This was generated by Midjourney..."]', 'Found it on an old forum');
    await page.fill('input[placeholder="https://..."]', 'https://example.com/original-source');

    // Click submit
    const attestationPromise = page.waitForResponse((res) => res.url().includes('/v1/attestations') && res.status() === 201);
    await page.click('button:has-text("Sign & Submit Attestation")');

    const attRes = await attestationPromise;
    expect(attRes.ok()).toBeTruthy();
  });
});
