import { test, expect } from '@playwright/test';
import * as path from 'path';

test.describe('Provenance Hunt Quest (e2e)', () => {
  // Use a predictable test image
  const fixturePath = path.resolve(__dirname, 'fixture.png');

  test('completes the full file drop to claim submission flow', async ({ page }) => {
    // Navigate to the drop zone
    await page.goto('/v');

    const resolvePromise = page.waitForResponse((res) => res.url().includes('/v1/subjects/resolve') && res.status() === 201);

    // 1. Upload File
    await page.locator('input[type="file"]').setInputFiles(fixturePath);

    // Wait for the resolve step to finish and redirect
    const resolveRes = await resolvePromise;
    expect(resolveRes.ok()).toBeTruthy();

    const resolveData = await resolveRes.json();
    expect(resolveData.subject?.hash).toBeDefined();

    // The page should redirect to /v/[hash]
    await page.waitForURL(`**/v/*`);

    // 2. Submit Claim
    // Wait for the minimal host page to load and display the summary
    await expect(page.locator('text=Subject Details')).toBeVisible();

    // Fill in the form
    await page.fill('textarea[placeholder="e.g. This was generated by Midjourney..."]', 'Found it on an old forum');
    await page.fill('input[placeholder="https://..."]', 'https://example.com/original-source');

    // Click submit
    const attestationPromise = page.waitForResponse((res) => res.url().includes('/v1/attestations') && res.status() === 201);
    await page.click('button:has-text("Sign & Submit Attestation")');

    const attRes = await attestationPromise;
    expect(attRes.ok()).toBeTruthy();
  });
});
