'use client';

import React, { useState } from 'react';
import { useClientIdentity } from '@/hooks/useClientIdentity';
import { signAttestation } from '@antiai/attestation-core';
import Link from 'next/link';

interface ProvenanceHuntFormProps {
  subjectHash: string;
  onSuccess?: () => void;
}

export function ProvenanceHuntForm({ subjectHash, onSuccess }: ProvenanceHuntFormProps) {
  const { identity, loading } = useClientIdentity();
  const [claimText, setClaimText] = useState('');
  const [sourceUrl, setSourceUrl] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (loading) {
    return <div className="p-4 rounded-xl bg-surface">Loading...</div>;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!claimText.trim()) return;

    setIsSubmitting(true);
    setError(null);

    try {
      let currentIdentity = identity;
      
      // 1. Lazy Onboarding
      if (!currentIdentity) {
        const { onboardIdentity, loadIdentity } = await import('@antiai/attestation-core/dist/client-identity');
        const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
        try {
          await onboardIdentity(apiUrl, 'WEB');
          const newlyLoaded = await loadIdentity();
          if (!newlyLoaded) throw new Error('Failed to load identity after onboard');
          currentIdentity = { ...newlyLoaded, id: newlyLoaded.id || 'primary' };
        } catch (err: any) {
          throw new Error(`Onboarding failed: ${err.message}`);
        }
      }

      // 2. Build claim
      // Fresh random nonce per envelope, always.
      const nonce = Array.from(crypto.getRandomValues(new Uint8Array(16)))
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');

      const payload = {
        version: '1.0',
        subject: { hash: subjectHash }, // In full impl, this would have perceptualHash and mediaType too
        claim: { 
          type: 'provenance_found', 
          payload: { sourceUrl: sourceUrl || undefined } 
        },
        attester: { 
          keyId: currentIdentity.keyId, 
          identityClass: 'pseudonymous' 
        },
        context: {
          domain: 'public',
          timestamp: new Date().toISOString(),
          nonce
        },
      };

      const signed = signAttestation(payload as any, currentIdentity.secretKey);

      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000'}/v1/attestations`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          payload: signed.payload,
          payloadHash: signed.payloadHash,
          signature: signed.signature
        }),
      });

      if (!res.ok) {
        // Implement error taxonomy handling
        if (res.status === 422) {
          // 'ATT_TIMESTAMP_SKEW' Auto-retry with server time in a real app
          throw new Error('Your device clock is off — please try again');
        } else if (res.status === 429) {
          throw new Error('Slow down — try again shortly');
        } else if (res.status === 403) {
          throw new Error('Re-establishing your verifier identity (Please refresh and try again)');
        } else if (res.status === 401 || res.status === 400) {
          throw new Error('Something went wrong signing — please report');
        }
        throw new Error(`Failed to submit attestation: ${await res.text()}`);
      }

      setClaimText('');
      setSourceUrl('');
      if (onSuccess) onSuccess();
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Failed to submit attestation.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="p-6 rounded-xl bg-surface border border-white/10">
      <h2 className="text-2xl font-bold mb-4">Add Provenance Claim</h2>
      
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-1">Context / Claim</label>
          <textarea 
            className="w-full bg-background border border-white/10 rounded-lg p-3 text-white"
            rows={3}
            placeholder="e.g. This was generated by Midjourney..."
            value={claimText}
            onChange={(e) => setClaimText(e.target.value)}
            required
            disabled={isSubmitting}
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">Source URL (Optional)</label>
          <input 
            type="url"
            className="w-full bg-background border border-white/10 rounded-lg p-3 text-white"
            placeholder="https://..."
            value={sourceUrl}
            onChange={(e) => setSourceUrl(e.target.value)}
            disabled={isSubmitting}
          />
        </div>

        {error && (
          <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg text-red-500 text-sm">
            {error}
          </div>
        )}

        <button 
          type="submit" 
          className="btn btn-primary w-full disabled:opacity-50"
          disabled={isSubmitting || !claimText.trim()}
        >
          {isSubmitting ? 'Signing & Submitting...' : 'Sign & Submit Attestation'}
        </button>
      </form>
    </div>
  );
}
